### Get all cats
GET http://localhost:3000/api/v1/cats

### Get cat by id
GET http://localhost:3000/api/v1/cats/41

### Add new cat
POST http://localhost:3000/api/v1/cats
Content-Type: application/json

{
"cat_name": "Garfield",
"weight": 7,
"owner": 37,
"filename": "garfield.jpg",
"birthdate": "2020-05-05"
}

### Get cats again
GET http://localhost:3000/api/v1/cats

### Get cats by user id
GET http://localhost:3000/api/v1/cats/user/37

### Update cat
PUT http://localhost:3000/api/v1/cats/41
Content-Type: application/json

{
  "cat_name": "Siiri Updated",
  "weight": 5,
  "owner": 37,
  "filename": "siiri.jpg",
  "birthdate": "2010-03-05"
}

### Delete cat
DELETE http://localhost:3000/api/v1/cats/43

### Add new cat WITH IMAGE
POST http://localhost:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

ImageCat
--MyBoundary
Content-Disposition: form-data; name="weight"

5
--MyBoundary
Content-Disposition: form-data; name="owner"

37
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2023-10-08
--MyBoundary
Content-Disposition: form-data; name="cat"; filename="dog.jpg"
Content-Type: image/jpeg

< ./dog.jpg
--MyBoundary--
