### Luo uusi käyttäjä
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "kakka User",
  "username": "kakka",
  "email": "kakka@example.com",
  "role": "admin",
  "password": "1234"
}

### POST login - onnistunut kirjautuminen
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kakka",
  "password": "1234"
}

### POST login - väärä salasana
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "kakka",
  "password": "12345"
}

### POST login - olematon käyttäjä
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "username": "olematon",
  "password": "test"
}
